// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcqeEb7k9BCr-PA7TYhR4XKI1YfpYgWO8',
    appId: '1:186947162120:web:6101d6dabfb82df70a01bd',
    messagingSenderId: '186947162120',
    projectId: 'onevest-678ae',
    authDomain: 'onevest-678ae.firebaseapp.com',
    storageBucket: 'onevest-678ae.firebasestorage.app',
    measurementId: 'G-GDXHF8897S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKuN6Hpwnl51nZsxHIP0eSGVlBUKoaHv4',
    appId: '1:186947162120:android:d2247c7cc79b54450a01bd',
    messagingSenderId: '186947162120',
    projectId: 'onevest-678ae',
    storageBucket: 'onevest-678ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeskZhg8vOPvVqEInUP-KtdwNfTDYJDHw',
    appId: '1:186947162120:ios:d7acc58dc6d5fde00a01bd',
    messagingSenderId: '186947162120',
    projectId: 'onevest-678ae',
    storageBucket: 'onevest-678ae.firebasestorage.app',
    iosBundleId: 'com.example.onevestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeskZhg8vOPvVqEInUP-KtdwNfTDYJDHw',
    appId: '1:186947162120:ios:d7acc58dc6d5fde00a01bd',
    messagingSenderId: '186947162120',
    projectId: 'onevest-678ae',
    storageBucket: 'onevest-678ae.firebasestorage.app',
    iosBundleId: 'com.example.onevestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcqeEb7k9BCr-PA7TYhR4XKI1YfpYgWO8',
    appId: '1:186947162120:web:cdf75cac5b2f1a190a01bd',
    messagingSenderId: '186947162120',
    projectId: 'onevest-678ae',
    authDomain: 'onevest-678ae.firebaseapp.com',
    storageBucket: 'onevest-678ae.firebasestorage.app',
    measurementId: 'G-7GP1KBY5ZZ',
  );
}
